server:
  port: 8081

spring:
  application:
    name: hormone-web-backend
  datasource:
    url: jdbc:mysql://localhost:3306/hormone_web?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: qwer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
